const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",

  VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export default ERROR_CODES;
